baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'ananke'

[menus]
[[menus.main]]
  name = 'Contact'
  url = '/contact'
  weight = 200
[[menus.main]]
  name = 'Posts'
  url = '/posts'
