name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to GCS
        run: |
          gsutil cp -r ./public/* gs://cs1660_assignment5/
